services:
  gradio-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rag-chatbot
    env_file:
      - .env
    ports:
      - "7860:7860"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
