# Created by Scalers AI for Dell Inc.

services:
  chat-ui:
    container_name: chat-ui
    build:
      context: ./chatbot-ui  
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    depends_on:
      - api-server
      - rasa
    environment:
      IP_ADDRESS: 122.199.161.12
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://api-server:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
  
  rasa:
    container_name: rasa
    build:
      context: ./rasa  
      dockerfile: Dockerfile
    ports:
      - 5005:5005
    depends_on:
      - api-server

  api-server:
    container_name: api-server
    build:
      context: ./api-server 
      dockerfile: Dockerfile
    volumes:
      - ./api-server/docs:/usr/src/api/docs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      MODEL_NAME: $MODEL_NAME
      PRECISION: $PRECISION
      HF_TOKEN: $HF_TOKEN
      DEVICE: $DEVICE
      MAX_NEW_TOKENS: $MAX_NEW_TOKENS
      TEMPERATURE: $TEMPERATURE
